### ISSUE TITLE
Quick analysis from bubblejail author

### ISSUE THREAD

**Issue by igo95862** [RalfJung/bubblebox#1]
Hello,

Thank you for mentioning bubblejail in your [blog post](https://www.ralfj.de/blog/2024/04/14/bubblebox.html). I noticed that  the traffic bubblejail's github page has significantly increased after it.

Looked through your code on and here are some thing I noticed:

https://github.com/RalfJung/bubblebox/blob/249a3635c23a8a543459fd084faf7ddb4241b06d/bubblebox.py#L5-L7

`XDG_RUNTIME_DIR` might not exist when running in non desktop environment. For example in CI.

https://github.com/RalfJung/bubblebox/blob/249a3635c23a8a543459fd084faf7ddb4241b06d/profiles.py#L45-L47

DISPLAY variable is much more complex. For example, `:0.1` is dislay 0 and screen 1 but it the actual socket is `/tmp/.X11-unix/X0`. [See this man page.](https://man.archlinux.org/man/X.7#DISPLAY_NAMES)

https://github.com/RalfJung/bubblebox/blob/249a3635c23a8a543459fd084faf7ddb4241b06d/profiles.py#L48

XAUTHORITY is not always present. Some environments run without it.

https://github.com/RalfJung/bubblebox/blob/249a3635c23a8a543459fd084faf7ddb4241b06d/profiles.py#L58

The D-Bus permissions are way to broad for notifications and screensaver. Some desktop environments acquire those names but export a lot more objects and interfaces under them. I recommend restricting object path and interface name with `--call` argument.

https://github.com/RalfJung/bubblebox/blob/249a3635c23a8a543459fd084faf7ddb4241b06d/bubblebox.py#L60-L74

I don't see the system socket being proxied? I've encountered several applications that don't work when system bus is missing while session bus is present.

**Comment by RalfJung** [comment]
Thanks for taking a look!

I am deliberately keeping things simple by just assuming all these env vars exist. The intended target audience for this script are people that will be able to change the sources themselves if they are in a sufficiently non-standard environment where there is no XDG_RUNTIME_PATH or no XAUTHORITY.

> The D-Bus permissions are way to broad for notifications and screensaver. Some desktop environments acquire those names but export a lot more objects and interfaces under them. I recommend restricting object path and interface name with --call argument.

I have seen `--call` used by some other xdg-dbus-proxy users, but I don't know enough about D-Bus to understand what the man page says about it. However, Flatpak configuration seems to also be in terms of `--talk`? At least that's what it looks like in Flatseal.

I guess I'll take a peak at what bubblejail does to get a starting point. :)

> I don't see the system socket being proxied? I've encountered several applications that don't work when system bus is missing while session bus is present.

Correct, I simply didn't have a need for this yet -- if in doubt I'd rather not have applications be able to access the system bus.

Are you saying it would be better to make the system bus exist but not actually allow access to anything, just so that applications can connect?

**Comment by igo95862** [comment]
> but I don't know enough about D-Bus to understand what the man page says about it.

`--call=org.freedesktop.Notifications=*@/org/freedesktop/Notifications` this rule allows the calling the `org.freedesktop.Notifications` bus and any interface on the `/org/freedesktop/Notifications` path. I recommend using the D-Feet debugger to explore the D-Bus and get familiar with it.

> Are you saying it would be better to make the system bus exist but not actually allow access to anything, just so that applications can connect?

In my experience certain applications break if system D-Bus is missing. I think it was Steam back in the day but they might have fixed that.

There is a trick in `xdg-dbus-proxy` there one process can act as multiple proxies and have different rules for each one. See the man page: `[ADDRESS PATH [OPTION...]...]` this means the ADDRESS PATH can be repeated multiple times.

**Comment by RalfJung** [comment]
> --call=org.freedesktop.Notifications=*@/org/freedesktop/Notifications this rule allows the calling the org.freedesktop.Notifications bus and any interface on the /org/freedesktop/Notifications path. I recommend using the D-Feet debugger to explore the D-Bus and get familiar with it.

I didn't quite realize that there are two dimensions here -- addresses on the bus (if that's the right term) and interfaces on the address.  But I think https://github.com/RalfJung/bubblebox/commit/e0e12077dafd2efd835ad6807dac4006795ea3d4 should resolve this concern.

> In my experience certain applications break if system D-Bus is missing. I think it was Steam back in the day but they might have fixed that.

Steam was one of the initial apps I tested this with, it works fine without the system bus.

But it was indeed easy to provide a fully filtered system bus to the sandbox, that is implemented in https://github.com/RalfJung/bubblebox/commit/1a71f2b54e8248af43e8d82a3c009a35a1d8f1aa.

**Comment by igo95862** [comment]
There are actually 4 dimensions:

![Screenshot](https://github.com/RalfJung/bubblebox/assets/8576552/f43a9e89-fa0c-451a-93ea-d966337b6bc8)

The bus name is the top level one. This is what `--see` and `--talk` allows for.

The `--call` alows to filter by object path, interface or method name.

**Comment by RalfJung** [comment]
Okay so I have now restricted the object path but not the interface, I think... but from how I understood the bubblejail sources, the same is happening there?

**Comment by igo95862** [comment]
Yes. I believe I wanted to check if blocking the interfaces like `org.freedesktop.DBus.Properties` would have negative impact but never could come around to do that.
